services:
  - type: web
    name: puppeteer-api
    env: node
    plan: free
    buildCommand: 'npm install && npx puppeteer install chrome'
    startCommand: 'node index.js'
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/google-chrome
